#!/bin/bash

# Script that lists files in the designated bucket
# Usage: s3list
# Anish Sujanani, December 2022

aws --profile $S3PERSONALSTORAGECLIPROFILE s3 ls --human-readable $S3PERSONALSTORAGEBUCKETPATH
